export const SETUP_FILES: readonly string[] = [
  "./tests/integration/support/world.ts",
  "./tests/integration/support/hooks.ts",
  "./tests/integration/support/steps/common.steps.ts",
  "./tests/integration/support/steps/config.steps.ts",
  "./tests/integration/support/steps/formatting.steps.ts",
  "./tests/integration/support/steps/driver-doc.steps.ts",
  "./tests/integration/support/steps/lsp.steps.ts",
  "./tests/integration/support/steps/review-signoff.steps.ts",
  "./tests/integration/support/steps/review-window.steps.ts",
  "./tests/integration/support/steps/steering.steps.ts",
  "./tests/integration/support/steps/repo-snapshot.steps.ts",
  "./tests/integration/support/steps/signal-exit.steps.ts",
  "./tests/integration/support/steps/tmpdir-gitdir.steps.ts",
]
